import type {
  CompetitionRecord,
  MatchBucket,
  MatchRecord,
  NewsItem,
  PlayerProfile,
  TeamRecord,
  UserPreferencesState,
  WorldCupTeamProfile,
} from "@/lib/types";

export const competitions: CompetitionRecord[] = [
  {
    id: "premier-league",
    slug: "premier-league",
    icon: "🏴",
    name: { zh: "英超", en: "Premier League" },
    region: "England",
  },
  {
    id: "la-liga",
    slug: "la-liga",
    icon: "🇪🇸",
    name: { zh: "西甲", en: "La Liga" },
    region: "Spain",
  },
  {
    id: "serie-a",
    slug: "serie-a",
    icon: "🇮🇹",
    name: { zh: "意甲", en: "Serie A" },
    region: "Italy",
  },
  {
    id: "bundesliga",
    slug: "bundesliga",
    icon: "🇩🇪",
    name: { zh: "德甲", en: "Bundesliga" },
    region: "Germany",
  },
  {
    id: "ligue-1",
    slug: "ligue-1",
    icon: "🇫🇷",
    name: { zh: "法甲", en: "Ligue 1" },
    region: "France",
  },
  {
    id: "champions-league",
    slug: "champions-league",
    icon: "⭐",
    name: { zh: "欧冠", en: "UEFA Champions League" },
    region: "Europe",
  },
  {
    id: "fifa-world-cup",
    slug: "fifa-world-cup",
    icon: "🌎",
    name: { zh: "世界杯", en: "FIFA World Cup" },
    region: "Global",
  },
];

export const teams: TeamRecord[] = [
  {
    id: "liverpool",
    slug: "liverpool",
    name: "Liverpool",
    shortName: "LIV",
    type: "club",
    country: "England",
    city: "Liverpool",
    color: "#C8102E",
    badge: "🔴",
  },
  {
    id: "man-city",
    slug: "man-city",
    name: "Man City",
    shortName: "MCI",
    type: "club",
    country: "England",
    city: "Manchester",
    color: "#6CABDD",
    badge: "🔵",
  },
  {
    id: "real-madrid",
    slug: "real-madrid",
    name: "Real Madrid",
    shortName: "RMA",
    type: "club",
    country: "Spain",
    city: "Madrid",
    color: "#FEBE10",
    badge: "⚪",
  },
  {
    id: "barcelona",
    slug: "barcelona",
    name: "Barcelona",
    shortName: "BAR",
    type: "club",
    country: "Spain",
    city: "Barcelona",
    color: "#A50044",
    badge: "🔵🔴",
  },
  {
    id: "inter",
    slug: "inter",
    name: "Inter",
    shortName: "INT",
    type: "club",
    country: "Italy",
    city: "Milan",
    color: "#00529F",
    badge: "⚫🔵",
  },
  {
    id: "napoli",
    slug: "napoli",
    name: "Napoli",
    shortName: "NAP",
    type: "club",
    country: "Italy",
    city: "Naples",
    color: "#0085CA",
    badge: "🔵",
  },
  {
    id: "bayern",
    slug: "bayern",
    name: "Bayern",
    shortName: "BAY",
    type: "club",
    country: "Germany",
    city: "Munich",
    color: "#DC052D",
    badge: "🔴⚪",
  },
  {
    id: "borussia-dortmund",
    slug: "borussia-dortmund",
    name: "Dortmund",
    shortName: "BVB",
    type: "club",
    country: "Germany",
    city: "Dortmund",
    color: "#FDE100",
    badge: "🟡",
  },
  {
    id: "paris-saint-germain",
    slug: "paris-saint-germain",
    name: "Paris SG",
    shortName: "PSG",
    type: "club",
    country: "France",
    city: "Paris",
    color: "#0A2A66",
    badge: "🔵🔴",
  },
  {
    id: "marseille",
    slug: "marseille",
    name: "Marseille",
    shortName: "OM",
    type: "club",
    country: "France",
    city: "Marseille",
    color: "#5EB6E4",
    badge: "🔵",
  },
  {
    id: "argentina",
    slug: "argentina",
    name: "Argentina",
    shortName: "ARG",
    type: "national",
    country: "Argentina",
    city: "Miami Camp",
    color: "#6EC1E4",
    badge: "🇦🇷",
  },
  {
    id: "france",
    slug: "france",
    name: "France",
    shortName: "FRA",
    type: "national",
    country: "France",
    city: "Houston Camp",
    color: "#1D4ED8",
    badge: "🇫🇷",
  },
  {
    id: "england",
    slug: "england",
    name: "England",
    shortName: "ENG",
    type: "national",
    country: "England",
    city: "New York Camp",
    color: "#D32F2F",
    badge: "🏴",
  },
  {
    id: "brazil",
    slug: "brazil",
    name: "Brazil",
    shortName: "BRA",
    type: "national",
    country: "Brazil",
    city: "Los Angeles Camp",
    color: "#F7D046",
    badge: "🇧🇷",
  },
];

export const matches: MatchRecord[] = [
  {
    id: "match-liv-mci",
    slug: "liverpool-vs-man-city",
    bucket: "today",
    competitionId: "premier-league",
    stage: "Matchday 34",
    kickoffLabel: "Sat, Apr 11 · 20:30",
    startsAt: "2026-04-11T20:30:00Z",
    venue: "Anfield, Liverpool",
    featuredPlayerSlug: "mo-salah",
    verdict: {
      zh: "曼城恢复窗口更完整，但利物浦主场和近期势头让这场比赛仍然维持五五开。",
      en: "City arrive fresher, but Liverpool's home edge keeps this matchup close to even.",
    },
    spotlight: {
      zh: "这是典型的“疲劳差距 vs 主场势头”对撞局。",
      en: "A classic collision between recovery edge and home momentum.",
    },
    home: {
      teamId: "liverpool",
      fatigue: 72,
      squadAvailability: 88,
      matchDensity: 4,
      restDays: 3,
      travelKm: 2840,
      recentResults: ["W", "W", "D", "W", "W"],
      momentumLabels: ["ARS(A)", "WOL(H)", "EVE(A)", "BOU(H)", "WHU(A)"],
      keyAbsent: ["Diogo Jota", "Harvey Elliott"],
      keyFatigued: [
        {
          playerSlug: "mo-salah",
          name: "Mo Salah",
          age: 33,
          minutes14d: 352,
          level: "high",
          note: {
            zh: "过去两周高负荷冲刺和终结动作叠加，恢复压力最大。",
            en: "Repeated sprint and finishing load has stayed near the top of the squad.",
          },
        },
        {
          playerSlug: "virgil-van-dijk",
          name: "Virgil van Dijk",
          age: 34,
          minutes14d: 360,
          level: "high",
          note: {
            zh: "连续首发且几乎打满，防线组织负荷偏高。",
            en: "Near-max minutes and constant line management keep his load elevated.",
          },
        },
        {
          playerSlug: "trent-alexander-arnold",
          name: "Trent Alexander-Arnold",
          age: 27,
          minutes14d: 310,
          level: "medium",
          note: {
            zh: "比赛负荷可控，但仍处于恢复观察窗口。",
            en: "Minutes are manageable, but he is still in a monitored recovery window.",
          },
        },
      ],
      schedule: [
        { day: -13, opponent: "ARS", home: false, competitionShort: "PL" },
        { day: -10, opponent: "ATM", home: true, competitionShort: "UCL" },
        { day: -6, opponent: "WOL", home: true, competitionShort: "PL" },
        { day: -3, opponent: "EVE", home: false, competitionShort: "PL" },
        { day: 0, opponent: "MCI", home: true, competitionShort: "PL", current: true },
        { day: 4, opponent: "PSG", home: false, competitionShort: "UCL" },
        { day: 7, opponent: "NEW", home: true, competitionShort: "PL" },
      ],
      aiSummary: {
        zh: "利物浦过去 14 天踢了 4 场，核心球员的连续出场让疲劳压力偏高。好消息是主场和最近的高压抢回球效率依然很强，这让他们的状态没有完全被赛程拖垮。",
        en: "Liverpool have stacked four matches in 14 days, and the core group is carrying a heavy minutes burden. The upside is that their home intensity and ball-winning rhythm remain strong enough to offset part of that fatigue.",
      },
      statusNote: {
        zh: "高疲劳不等于低战斗力，但会明显放大比赛后 30 分钟的波动。",
        en: "High fatigue does not kill competitiveness, but it usually widens late-game variance.",
      },
      formationHealth: {
        available: 8,
        doubtful: 1,
        absent: 2,
      },
    },
    away: {
      teamId: "man-city",
      fatigue: 45,
      squadAvailability: 92,
      matchDensity: 2,
      restDays: 6,
      travelKm: 680,
      recentResults: ["W", "L", "W", "D", "W"],
      momentumLabels: ["CHE(H)", "TOT(A)", "NFO(H)", "BHA(A)", "LEI(H)"],
      keyAbsent: ["Óscar Bobb"],
      keyFatigued: [
        {
          playerSlug: "erling-haaland",
          name: "Erling Haaland",
          age: 25,
          minutes14d: 248,
          level: "medium",
          note: {
            zh: "中负荷但冲刺频率高，仍需赛前观察。",
            en: "A managed minute load with plenty of top-end sprinting still needs monitoring.",
          },
        },
        {
          playerSlug: "rodri",
          name: "Rodri",
          age: 29,
          minutes14d: 180,
          level: "low",
          note: {
            zh: "恢复完整，是曼城节奏控制的最大体能优势。",
            en: "Fully recovered and central to City's rhythm control advantage.",
          },
        },
      ],
      schedule: [
        { day: -12, opponent: "CHE", home: true, competitionShort: "PL" },
        { day: -5, opponent: "NFO", home: true, competitionShort: "PL" },
        { day: 0, opponent: "LIV", home: false, competitionShort: "PL", current: true },
        { day: 4, opponent: "BRU", home: true, competitionShort: "UCL" },
        { day: 8, opponent: "ARS", home: false, competitionShort: "PL" },
      ],
      aiSummary: {
        zh: "曼城近两周只踢了 2 场，旅行量也明显更低，因此赛前恢复窗口更完整。阵容可用率和中场控制点都更稳定，但安菲尔德客场仍会放大比赛的不确定性。",
        en: "City have played only twice across the last two weeks and have travelled far less, so the recovery window is cleaner. Availability and midfield control are more stable, but Anfield still injects a lot of volatility into the game.",
      },
      statusNote: {
        zh: "更轻的赛程让他们更像一支能按自己节奏压比赛的球队。",
        en: "The lighter schedule makes them look more capable of imposing their own tempo.",
      },
      formationHealth: {
        available: 9,
        doubtful: 1,
        absent: 1,
      },
    },
  },
  {
    id: "match-rma-bar",
    slug: "real-madrid-vs-barcelona",
    bucket: "tomorrow",
    competitionId: "la-liga",
    stage: "Jornada 32",
    kickoffLabel: "Sun, Apr 12 · 21:00",
    startsAt: "2026-04-12T21:00:00Z",
    venue: "Santiago Bernabéu, Madrid",
    featuredPlayerSlug: "jude-bellingham",
    verdict: {
      zh: "皇马体能压力更大，巴萨则在完整度和恢复节奏上都更平稳。",
      en: "Madrid carry the heavier physical load while Barca arrive in a calmer recovery state.",
    },
    spotlight: {
      zh: "这场国家德比更像阵容深度和恢复质量的直接对撞。",
      en: "This Clasico is leaning toward a depth and recovery-quality battle.",
    },
    home: {
      teamId: "real-madrid",
      fatigue: 68,
      squadAvailability: 82,
      matchDensity: 5,
      restDays: 2,
      travelKm: 3200,
      recentResults: ["W", "W", "L", "W", "D"],
      momentumLabels: ["SEV(A)", "BAY(A)", "VIL(H)", "ATM(A)", "BAY(H)"],
      keyAbsent: ["Aurélien Tchouaméni", "Eduardo Camavinga", "Dani Carvajal"],
      keyFatigued: [
        {
          playerSlug: "vinicius-jr",
          name: "Vinícius Jr",
          age: 25,
          minutes14d: 380,
          level: "high",
          note: {
            zh: "连续高强度推进和一对一动作，使其成为全队最重负荷点。",
            en: "Successive isolation actions and direct carries make him the team's heaviest load point.",
          },
        },
        {
          playerSlug: "jude-bellingham",
          name: "Jude Bellingham",
          age: 22,
          minutes14d: 340,
          level: "medium",
          note: {
            zh: "前插与回追两端都承担大量任务，恢复质量决定上限。",
            en: "His box-to-box role keeps both attacking and recovery load high.",
          },
        },
      ],
      schedule: [
        { day: -14, opponent: "SEV", home: false, competitionShort: "LL" },
        { day: -11, opponent: "BAY", home: false, competitionShort: "UCL" },
        { day: -7, opponent: "VIL", home: true, competitionShort: "LL" },
        { day: -4, opponent: "ATM", home: false, competitionShort: "LL" },
        { day: -1, opponent: "BAY", home: true, competitionShort: "UCL" },
        { day: 0, opponent: "BAR", home: true, competitionShort: "LL", current: true },
        { day: 5, opponent: "VAL", home: false, competitionShort: "LL" },
      ],
      aiSummary: {
        zh: "皇马在 14 天内打了 5 场，其中包含两回合欧冠和一场高对抗德比。赛程与伤缺叠加后，中前场核心球员的负荷分布已经逼近风险区。",
        en: "Madrid have squeezed five matches into 14 days, including a two-leg Champions League tie and a derby. With injuries layered on top, the load on their core attacking spine is drifting close to the risk zone.",
      },
      statusNote: {
        zh: "如果比赛被拖进高节奏拉扯，皇马后段体能波动会更明显。",
        en: "If the match becomes stretched, Madrid are more likely to show late-game physical drop-off.",
      },
      formationHealth: {
        available: 7,
        doubtful: 2,
        absent: 2,
      },
    },
    away: {
      teamId: "barcelona",
      fatigue: 52,
      squadAvailability: 95,
      matchDensity: 3,
      restDays: 5,
      travelKm: 1100,
      recentResults: ["W", "W", "W", "W", "D"],
      momentumLabels: ["RSO(H)", "BET(A)", "ESP(H)", "GIR(A)", "MAL(H)"],
      keyAbsent: ["Frenkie de Jong"],
      keyFatigued: [
        {
          playerSlug: "lamine-yamal",
          name: "Lamine Yamal",
          age: 18,
          minutes14d: 260,
          level: "low",
          note: {
            zh: "使用频率稳定，但恢复窗口充足。",
            en: "Usage remains high, but the recovery window has been healthy.",
          },
        },
        {
          playerSlug: "pedri",
          name: "Pedri",
          age: 23,
          minutes14d: 285,
          level: "medium",
          note: {
            zh: "仍需控制累计负荷，但当前不在高风险区。",
            en: "Accumulated minutes still need care, though he is not in the red right now.",
          },
        },
      ],
      schedule: [
        { day: -11, opponent: "RSO", home: true, competitionShort: "LL" },
        { day: -7, opponent: "BET", home: false, competitionShort: "LL" },
        { day: -3, opponent: "ESP", home: true, competitionShort: "LL" },
        { day: 0, opponent: "RMA", home: false, competitionShort: "LL", current: true },
        { day: 4, opponent: "LIL", home: true, competitionShort: "UCL" },
      ],
      aiSummary: {
        zh: "巴萨的赛程更温和，阵容完整度也保持在高位，因此整体状态更平稳。球队近五场的攻守节奏和比赛掌控感都在上升，这让他们的赛前画像更干净。",
        en: "Barca arrive on a softer schedule with a deeper level of squad availability, so the overall state is steadier. Their control on both sides of the ball has improved over the last five, which creates a cleaner pre-match profile.",
      },
      statusNote: {
        zh: "如果比赛进入阵地控制阶段，巴萨会更舒服。",
        en: "If the game slows into structured possession, Barca should feel more comfortable.",
      },
      formationHealth: {
        available: 10,
        doubtful: 0,
        absent: 1,
      },
    },
  },
  {
    id: "match-int-nap",
    slug: "inter-vs-napoli",
    bucket: "today",
    competitionId: "serie-a",
    stage: "Round 32",
    kickoffLabel: "Sat, Apr 11 · 22:00",
    startsAt: "2026-04-11T22:00:00Z",
    venue: "San Siro, Milan",
    featuredPlayerSlug: "lautaro-martinez",
    verdict: {
      zh: "国米的主场节奏更稳定，但那不勒斯的恢复窗口更干净，这场更像压迫质量和终结效率的对撞。",
      en: "Inter own the steadier home rhythm, but Napoli arrive with the cleaner recovery window, so this one looks like a clash between pressure quality and finishing efficiency.",
    },
    spotlight: {
      zh: "意甲强强对话里，体能优势往往先体现在中场覆盖和反击回防速度上。",
      en: "In a top Serie A matchup, the fatigue edge usually appears first in midfield coverage and transition recovery.",
    },
    home: {
      teamId: "inter",
      fatigue: 57,
      squadAvailability: 90,
      matchDensity: 3,
      restDays: 4,
      travelKm: 620,
      recentResults: ["W", "D", "W", "W", "W"],
      momentumLabels: ["LAZ(H)", "TOR(A)", "UDI(H)", "ROM(A)", "MIL(H)"],
      keyAbsent: ["Benjamin Pavard"],
      keyFatigued: [
        {
          playerSlug: "lautaro-martinez",
          name: "Lautaro Martinez",
          age: 29,
          minutes14d: 318,
          level: "medium",
          note: {
            zh: "持续承担终结任务，但整体仍处于可管理区间。",
            en: "He keeps carrying the finishing load, though it still sits in a manageable zone.",
          },
        },
        {
          name: "Nicolo Barella",
          age: 28,
          minutes14d: 294,
          level: "medium",
          note: {
            zh: "覆盖面积大，对比赛后段体能要求更高。",
            en: "His range keeps the late-game physical demand high.",
          },
        },
      ],
      schedule: [
        { day: -10, opponent: "LAZ", home: true, competitionShort: "SA" },
        { day: -6, opponent: "TOR", home: false, competitionShort: "SA" },
        { day: -3, opponent: "UDI", home: true, competitionShort: "SA" },
        { day: 0, opponent: "NAP", home: true, competitionShort: "SA", current: true },
        { day: 4, opponent: "FIO", home: false, competitionShort: "SA" },
      ],
      aiSummary: {
        zh: "国米最近的赛程虽不算极端，但中轴线球员连续承担组织和终结任务，体能并不轻松。主场环境和阵地战熟练度依然是他们最大的稳定器。",
        en: "Inter's recent schedule has not been extreme, but the spine is still stacking creative and finishing load. Home control and positional familiarity remain their biggest stabilizers.",
      },
      statusNote: {
        zh: "如果比赛进入高对抗中场绞杀，国米的轮换深度会变得更关键。",
        en: "If the match becomes a midfield wrestling contest, Inter's rotation depth becomes more important.",
      },
      formationHealth: { available: 9, doubtful: 1, absent: 1 },
    },
    away: {
      teamId: "napoli",
      fatigue: 49,
      squadAvailability: 86,
      matchDensity: 2,
      restDays: 6,
      travelKm: 780,
      recentResults: ["W", "W", "L", "D", "W"],
      momentumLabels: ["LEC(H)", "ATA(A)", "TOR(H)", "BOL(A)", "EMP(H)"],
      keyAbsent: ["Stanislav Lobotka", "Mathias Olivera"],
      keyFatigued: [
        {
          name: "Khvicha Kvaratskhelia",
          age: 25,
          minutes14d: 246,
          level: "medium",
          note: {
            zh: "持球推进和一对一动作频率高，但恢复相对完整。",
            en: "Carry and isolation volume remains high, but the recovery rhythm has been decent.",
          },
        },
        {
          name: "Giovanni Di Lorenzo",
          age: 32,
          minutes14d: 270,
          level: "medium",
          note: {
            zh: "两端往返多，负荷比较平均。",
            en: "The two-way fullback load is balanced but persistent.",
          },
        },
      ],
      schedule: [
        { day: -11, opponent: "LEC", home: true, competitionShort: "SA" },
        { day: -7, opponent: "ATA", home: false, competitionShort: "SA" },
        { day: -3, opponent: "TOR", home: true, competitionShort: "SA" },
        { day: 0, opponent: "INT", home: false, competitionShort: "SA", current: true },
        { day: 5, opponent: "GEN", home: true, competitionShort: "SA" },
      ],
      aiSummary: {
        zh: "那不勒斯近两周赛程更轻，旅行压力也有限，因此赛前体能轮廓更整洁。问题在于阵容完整度稍逊，关键位置的替换空间没有国米宽。",
        en: "Napoli have faced a lighter two-week schedule with limited travel, so the physical profile is cleaner. The tradeoff is thinner depth in a few key positions compared with Inter.",
      },
      statusNote: {
        zh: "他们更适合把比赛拖进转换和纵向冲击节奏。",
        en: "They are more comfortable if the game leans toward transitions and vertical attacks.",
      },
      formationHealth: { available: 8, doubtful: 1, absent: 2 },
    },
  },
  {
    id: "match-bay-bvb",
    slug: "bayern-vs-dortmund",
    bucket: "tomorrow",
    competitionId: "bundesliga",
    stage: "Matchday 29",
    kickoffLabel: "Sun, Apr 12 · 18:30",
    startsAt: "2026-04-12T18:30:00Z",
    venue: "Allianz Arena, Munich",
    featuredPlayerSlug: "jamal-musiala",
    verdict: {
      zh: "拜仁恢复窗口更完整，多特则带着更重的追赶负荷进入比赛，主队的节奏掌控面更大。",
      en: "Bayern have the cleaner recovery window while Dortmund arrive carrying the heavier chase load, so the host side owns more of the tempo-control upside.",
    },
    spotlight: {
      zh: "德甲强对话里，高位压迫是否能持续 90 分钟通常就是比赛分水岭。",
      en: "In a heavyweight Bundesliga clash, whether the press survives 90 minutes is often the true separator.",
    },
    home: {
      teamId: "bayern",
      fatigue: 54,
      squadAvailability: 91,
      matchDensity: 3,
      restDays: 5,
      travelKm: 720,
      recentResults: ["W", "W", "D", "W", "W"],
      momentumLabels: ["B04(A)", "MAI(H)", "FRE(A)", "RBL(H)", "KOE(H)"],
      keyAbsent: ["Kingsley Coman"],
      keyFatigued: [
        {
          playerSlug: "jamal-musiala",
          name: "Jamal Musiala",
          age: 23,
          minutes14d: 290,
          level: "medium",
          note: {
            zh: "高频变向和持球推进让他的爆发动作负荷偏高。",
            en: "Frequent direction changes and carries keep the explosive load elevated.",
          },
        },
        {
          name: "Joshua Kimmich",
          age: 31,
          minutes14d: 276,
          level: "low",
          note: {
            zh: "恢复质量不错，是节奏控制点。",
            en: "Recovery has been solid, and he remains the rhythm control point.",
          },
        },
      ],
      schedule: [
        { day: -11, opponent: "B04", home: false, competitionShort: "BL" },
        { day: -7, opponent: "MAI", home: true, competitionShort: "BL" },
        { day: -3, opponent: "FRE", home: false, competitionShort: "BL" },
        { day: 0, opponent: "BVB", home: true, competitionShort: "BL", current: true },
        { day: 4, opponent: "STU", home: false, competitionShort: "BL" },
      ],
      aiSummary: {
        zh: "拜仁的比赛节奏和恢复安排都更平衡，因此主场开局通常会更主动。真正要关注的是穆西亚拉和边路组合是否需要在下半场被精细管理。",
        en: "Bayern are sitting on the more balanced rhythm and recovery plan, so the home start should be assertive. The real watchpoint is whether Musiala and the wide pair need second-half load management.",
      },
      statusNote: {
        zh: "如果比赛进入持续压迫，拜仁更像能稳定维持强度的一方。",
        en: "If the game becomes a sustained pressing battle, Bayern look better equipped to hold their level.",
      },
      formationHealth: { available: 9, doubtful: 1, absent: 1 },
    },
    away: {
      teamId: "borussia-dortmund",
      fatigue: 63,
      squadAvailability: 84,
      matchDensity: 4,
      restDays: 3,
      travelKm: 980,
      recentResults: ["W", "L", "W", "D", "W"],
      momentumLabels: ["WOB(H)", "SGE(A)", "AUG(H)", "BMG(A)", "BOC(H)"],
      keyAbsent: ["Nico Schlotterbeck", "Karim Adeyemi"],
      keyFatigued: [
        {
          name: "Julian Brandt",
          age: 30,
          minutes14d: 308,
          level: "medium",
          note: {
            zh: "组织和反抢双重任务让他处于观察区。",
            en: "Creative work plus counter-press duties put him in the watch zone.",
          },
        },
        {
          name: "Emre Can",
          age: 32,
          minutes14d: 326,
          level: "high",
          note: {
            zh: "中后场清理任务太重，后段波动风险明显。",
            en: "The defensive cleaning load is heavy and raises late-game volatility.",
          },
        },
      ],
      schedule: [
        { day: -10, opponent: "WOB", home: true, competitionShort: "BL" },
        { day: -6, opponent: "SGE", home: false, competitionShort: "BL" },
        { day: -3, opponent: "AUG", home: true, competitionShort: "BL" },
        { day: 0, opponent: "BAY", home: false, competitionShort: "BL", current: true },
        { day: 5, opponent: "BRE", home: true, competitionShort: "BL" },
      ],
      aiSummary: {
        zh: "多特最近的比赛节奏更碎，恢复窗口也偏短，因此赛前体能压力更大。好消息是他们的纵向冲击和定位球威胁仍足够让比赛保持开放。",
        en: "Dortmund's recent rhythm has been choppier and the recovery windows shorter, so the physical pressure is higher. The upside is that their vertical attacks and set-piece threat still keep the game open.",
      },
      statusNote: {
        zh: "如果能把比赛拉成开放对攻，多特的机会会明显增加。",
        en: "If they can stretch the game into an open exchange, Dortmund's chances improve a lot.",
      },
      formationHealth: { available: 8, doubtful: 1, absent: 2 },
    },
  },
  {
    id: "match-int-bay",
    slug: "inter-vs-bayern",
    bucket: "week",
    competitionId: "champions-league",
    stage: "Semi-final 1st leg",
    kickoffLabel: "Wed, Apr 15 · 20:00",
    startsAt: "2026-04-15T20:00:00Z",
    venue: "San Siro, Milan",
    featuredPlayerSlug: "lautaro-martinez",
    verdict: {
      zh: "国米赛程稍重但主场优势明显，拜仁的恢复质量更稳，属于强度很高的均衡对局。",
      en: "Inter have the home edge, Bayern hold the cleaner recovery profile, and the matchup feels finely balanced.",
    },
    spotlight: {
      zh: "欧冠强强对话里，旅行和轮换质量会比近期战绩更重要。",
      en: "In a top Champions League tie, travel and rotation quality may matter more than raw form.",
    },
    home: {
      teamId: "inter",
      fatigue: 61,
      squadAvailability: 86,
      matchDensity: 4,
      restDays: 4,
      travelKm: 1640,
      recentResults: ["W", "D", "W", "W", "L"],
      momentumLabels: ["ROM(H)", "NAP(A)", "LAZ(H)", "TOR(A)", "JUV(H)"],
      keyAbsent: ["Benjamin Pavard"],
      keyFatigued: [
        {
          playerSlug: "lautaro-martinez",
          name: "Lautaro Martínez",
          age: 29,
          minutes14d: 318,
          level: "medium",
          note: {
            zh: "射门和对抗密度都高，但恢复还在可控区间。",
            en: "Shot volume and duels remain high, though the recovery load is still manageable.",
          },
        },
        {
          name: "Hakan Çalhanoğlu",
          age: 32,
          minutes14d: 305,
          level: "medium",
          note: {
            zh: "中场组织与定位球负荷并存。",
            en: "Playmaking and set-piece responsibilities are stacking together.",
          },
        },
      ],
      schedule: [
        { day: -10, opponent: "ROM", home: true, competitionShort: "SA" },
        { day: -7, opponent: "NAP", home: false, competitionShort: "SA" },
        { day: -3, opponent: "LAZ", home: true, competitionShort: "SA" },
        { day: 0, opponent: "BAY", home: true, competitionShort: "UCL", current: true },
        { day: 4, opponent: "MIL", home: false, competitionShort: "SA" },
      ],
      aiSummary: {
        zh: "国米的负荷略高于理想区间，但还没有出现明显透支点。真正值得关注的是中轴线球员连续承担组织任务后的恢复效率。",
        en: "Inter are a bit above the ideal workload zone, but there is no obvious red flag yet. The key question is how efficiently the spine recovers after another cycle of creative responsibility.",
      },
      statusNote: {
        zh: "主场环境会帮他们把体能压力转化成更直接的前场压迫。",
        en: "The home environment should help turn that load into front-foot pressure.",
      },
      formationHealth: { available: 9, doubtful: 1, absent: 1 },
    },
    away: {
      teamId: "bayern",
      fatigue: 49,
      squadAvailability: 89,
      matchDensity: 3,
      restDays: 5,
      travelKm: 970,
      recentResults: ["W", "W", "D", "W", "W"],
      momentumLabels: ["BVB(H)", "MAI(A)", "RBL(H)", "LEV(A)", "STU(H)"],
      keyAbsent: ["Kingsley Coman"],
      keyFatigued: [
        {
          name: "Jamal Musiala",
          age: 23,
          minutes14d: 290,
          level: "medium",
          note: {
            zh: "高强度变向多，但比赛密度仍可承受。",
            en: "High change-of-direction load, but the schedule is still manageable.",
          },
        },
        {
          name: "Joshua Kimmich",
          age: 31,
          minutes14d: 276,
          level: "low",
          note: {
            zh: "节奏控制点恢复良好。",
            en: "Core rhythm controller, arriving in good condition.",
          },
        },
      ],
      schedule: [
        { day: -11, opponent: "BVB", home: true, competitionShort: "BL" },
        { day: -7, opponent: "MAI", home: false, competitionShort: "BL" },
        { day: -3, opponent: "RBL", home: true, competitionShort: "BL" },
        { day: 0, opponent: "INT", home: false, competitionShort: "UCL", current: true },
        { day: 4, opponent: "LEV", home: false, competitionShort: "BL" },
      ],
      aiSummary: {
        zh: "拜仁的恢复窗口更整齐，旅行压力也相对可控，因此整体赛前状态更平衡。只要前场核心不被迫连续打满，他们的节奏完整性会是优势点。",
        en: "Bayern's recovery windows are cleaner and travel pressure is more manageable, so the overall condition board looks balanced. If the front line avoids another full-load outing, rhythm continuity should remain an advantage.",
      },
      statusNote: {
        zh: "他们更像一支能在两回合里持续保持稳定输出的球队。",
        en: "They look like the side more likely to sustain stable output across two legs.",
      },
      formationHealth: { available: 9, doubtful: 1, absent: 1 },
    },
  },
  {
    id: "match-rma-psg",
    slug: "real-madrid-vs-psg",
    bucket: "week",
    competitionId: "champions-league",
    stage: "Semi-final 1st leg",
    kickoffLabel: "Thu, Apr 16 · 21:00",
    startsAt: "2026-04-16T21:00:00Z",
    venue: "Santiago Bernabeu, Madrid",
    featuredPlayerSlug: "jude-bellingham",
    verdict: {
      zh: "皇马的赛程压力更大，巴黎的恢复窗口更整齐，因此这组对决的胜负更像负荷管理质量的比拼。",
      en: "Madrid are carrying the heavier schedule, while PSG arrive on the cleaner recovery line, turning this tie into a test of load management quality.",
    },
    spotlight: {
      zh: "越到欧冠后段，爆发型边锋能否连续输出往往比单场状态更关键。",
      en: "Late in the Champions League, repeatability from explosive wide players often matters more than one-game form.",
    },
    home: {
      teamId: "real-madrid",
      fatigue: 67,
      squadAvailability: 84,
      matchDensity: 5,
      restDays: 3,
      travelKm: 1220,
      recentResults: ["W", "W", "D", "W", "L"],
      momentumLabels: ["SEV(A)", "VAL(H)", "ATM(A)", "VIL(H)", "BAR(H)"],
      keyAbsent: ["Ferland Mendy"],
      keyFatigued: [
        {
          playerSlug: "jude-bellingham",
          name: "Jude Bellingham",
          age: 22,
          minutes14d: 340,
          level: "high",
          note: {
            zh: "连续承担覆盖、推进和反抢，负荷已经逼近风险线。",
            en: "Repeated coverage, carries and counter-press work have pushed him close to the risk line.",
          },
        },
        {
          name: "Federico Valverde",
          age: 28,
          minutes14d: 332,
          level: "high",
          note: {
            zh: "攻防往返和补位负荷都非常重。",
            en: "The two-way running and emergency coverage load remain very high.",
          },
        },
      ],
      schedule: [
        { day: -10, opponent: "SEV", home: false, competitionShort: "LL" },
        { day: -7, opponent: "VAL", home: true, competitionShort: "LL" },
        { day: -4, opponent: "ATM", home: false, competitionShort: "LL" },
        { day: 0, opponent: "PSG", home: true, competitionShort: "UCL", current: true },
        { day: 4, opponent: "GET", home: true, competitionShort: "LL" },
      ],
      aiSummary: {
        zh: "皇马的问题不是单点状态，而是中前场核心已经连续处在高使用率区间。主场优势依旧明显，但这场更像对恢复质量和替补深度的考验。",
        en: "Madrid's issue is not one player form but the sustained high usage of the attacking spine. The home edge remains real, but this is increasingly a test of recovery quality and bench depth.",
      },
      statusNote: {
        zh: "如果不能在上半场建立优势，后段强度波动会放大。",
        en: "If they do not create separation early, late-game volatility will rise.",
      },
      formationHealth: { available: 8, doubtful: 1, absent: 1 },
    },
    away: {
      teamId: "paris-saint-germain",
      fatigue: 50,
      squadAvailability: 92,
      matchDensity: 3,
      restDays: 5,
      travelKm: 940,
      recentResults: ["W", "W", "W", "D", "W"],
      momentumLabels: ["REN(H)", "LIL(A)", "OM(H)", "NIC(A)", "MON(H)"],
      keyAbsent: [],
      keyFatigued: [
        {
          playerSlug: "ousmane-dembele",
          name: "Ousmane Dembele",
          age: 29,
          minutes14d: 262,
          level: "medium",
          note: {
            zh: "一对一动作密度高，但分钟管理明显比皇马更从容。",
            en: "The 1v1 load is still high, but the minute management has been much cleaner than Madrid's.",
          },
        },
        {
          name: "Vitinha",
          age: 26,
          minutes14d: 228,
          level: "low",
          note: {
            zh: "节奏控制点恢复窗口健康。",
            en: "The midfield rhythm control point is arriving on a healthy recovery window.",
          },
        },
      ],
      schedule: [
        { day: -10, opponent: "REN", home: true, competitionShort: "L1" },
        { day: -7, opponent: "LIL", home: false, competitionShort: "L1" },
        { day: -3, opponent: "OM", home: true, competitionShort: "L1" },
        { day: 0, opponent: "RMA", home: false, competitionShort: "UCL", current: true },
        { day: 4, opponent: "MON", home: true, competitionShort: "L1" },
      ],
      aiSummary: {
        zh: "巴黎的赛程密度没有那么夸张，主力边锋和中场核心的出场也更受控，因此首回合的赛前状态更整洁。关键在于他们能否把这种优势转成中后段的速度优势。",
        en: "PSG are not carrying the same density, and the key winger-midfield minutes have been more controlled, leaving a cleaner pre-match profile. The question is whether they can turn that edge into second-half pace advantage.",
      },
      statusNote: {
        zh: "如果节奏被拉快，巴黎更像能连续做出高质量冲刺的一方。",
        en: "If the tempo rises, PSG look likelier to repeat high-value sprints.",
      },
      formationHealth: { available: 10, doubtful: 0, absent: 0 },
    },
  },
  {
    id: "match-bar-bvb-ucl",
    slug: "barcelona-vs-dortmund-ucl",
    bucket: "week",
    competitionId: "champions-league",
    stage: "Semi-final 1st leg",
    kickoffLabel: "Tue, Apr 14 · 20:00",
    startsAt: "2026-04-14T20:00:00Z",
    venue: "Estadi Olimpic, Barcelona",
    featuredPlayerSlug: "lamine-yamal",
    verdict: {
      zh: "巴萨的恢复窗口和阵容完整度都更占优，多特则需要把比赛拖进更高波动的开放节奏。",
      en: "Barca hold the better recovery window and availability profile, while Dortmund need a more volatile and open game state.",
    },
    spotlight: {
      zh: "这组半决赛更像“控制节奏”与“制造混乱”的对撞。",
      en: "This semi-final feels like a collision between rhythm control and chaos creation.",
    },
    home: {
      teamId: "barcelona",
      fatigue: 44,
      squadAvailability: 93,
      matchDensity: 2,
      restDays: 6,
      travelKm: 420,
      recentResults: ["W", "W", "D", "W", "W"],
      momentumLabels: ["GIR(H)", "SOC(A)", "BET(H)", "VAL(A)", "SEV(H)"],
      keyAbsent: [],
      keyFatigued: [
        {
          playerSlug: "lamine-yamal",
          name: "Lamine Yamal",
          age: 18,
          minutes14d: 260,
          level: "low",
          note: {
            zh: "使用率高，但恢复质量依然健康。",
            en: "Usage remains aggressive, but the recovery profile still looks healthy.",
          },
        },
        {
          name: "Pedri",
          age: 24,
          minutes14d: 246,
          level: "low",
          note: {
            zh: "中场节奏组织的负荷处于理想区间。",
            en: "Midfield control work is sitting in the ideal zone.",
          },
        },
      ],
      schedule: [
        { day: -11, opponent: "GIR", home: true, competitionShort: "LL" },
        { day: -7, opponent: "SOC", home: false, competitionShort: "LL" },
        { day: -3, opponent: "BET", home: true, competitionShort: "LL" },
        { day: 0, opponent: "BVB", home: true, competitionShort: "UCL", current: true },
        { day: 4, opponent: "VAL", home: false, competitionShort: "LL" },
      ],
      aiSummary: {
        zh: "巴萨近两周的比赛密度和旅行负荷都保持在舒服区间，阵容完整度也很高，因此他们更有能力按自己的节奏组织比赛。",
        en: "Barca have kept both recent density and travel load in a comfortable zone, and availability remains high, giving them more control over the pace of the tie.",
      },
      statusNote: {
        zh: "他们最理想的局面是把比赛拖进持续控球和阵地组织。",
        en: "Their ideal script is a long spell of possession control and organized attacks.",
      },
      formationHealth: { available: 10, doubtful: 0, absent: 0 },
    },
    away: {
      teamId: "borussia-dortmund",
      fatigue: 62,
      squadAvailability: 82,
      matchDensity: 4,
      restDays: 3,
      travelKm: 1680,
      recentResults: ["W", "L", "W", "D", "W"],
      momentumLabels: ["WOB(H)", "SGE(A)", "AUG(H)", "BMG(A)", "BOC(H)"],
      keyAbsent: ["Nico Schlotterbeck", "Karim Adeyemi"],
      keyFatigued: [
        {
          name: "Julian Brandt",
          age: 30,
          minutes14d: 308,
          level: "medium",
          note: {
            zh: "组织和反抢任务叠加，让他处在观察区。",
            en: "The combination of chance creation and counter-pressing keeps him in the watch zone.",
          },
        },
        {
          name: "Emre Can",
          age: 32,
          minutes14d: 326,
          level: "high",
          note: {
            zh: "后场清理和覆盖负担都已经偏重。",
            en: "The defensive cleaning and coverage burden is already heavy.",
          },
        },
      ],
      schedule: [
        { day: -10, opponent: "WOB", home: true, competitionShort: "BL" },
        { day: -6, opponent: "SGE", home: false, competitionShort: "BL" },
        { day: -3, opponent: "AUG", home: true, competitionShort: "BL" },
        { day: 0, opponent: "BAR", home: false, competitionShort: "UCL", current: true },
        { day: 5, opponent: "BRE", home: true, competitionShort: "BL" },
      ],
      aiSummary: {
        zh: "多特还是那种一旦比赛进入开放对冲就很危险的球队，但以当前负荷和旅行情况来看，他们更难在 90 分钟里持续维持高质量压迫。",
        en: "Dortmund remain dangerous if the tie opens up into transitions, but the current load and travel picture make it harder to sustain high-quality pressure for 90 minutes.",
      },
      statusNote: {
        zh: "他们需要更多短时间高收益回合，而不是持续控场。",
        en: "They need short bursts of high-value chaos rather than long phases of control.",
      },
      formationHealth: { available: 8, doubtful: 1, absent: 2 },
    },
  },
  {
    id: "match-psg-om",
    slug: "psg-vs-marseille",
    bucket: "week",
    competitionId: "ligue-1",
    stage: "Week 31",
    kickoffLabel: "Sun, Apr 19 · 20:45",
    startsAt: "2026-04-19T20:45:00Z",
    venue: "Parc des Princes, Paris",
    featuredPlayerSlug: "ousmane-dembele",
    verdict: {
      zh: "巴黎的恢复质量和阵容完整度都更稳，马赛则需要把比赛拖进更高波动的开放节奏。",
      en: "PSG hold the cleaner recovery and availability profile, while Marseille need a more volatile open game to tilt the balance.",
    },
    spotlight: {
      zh: "法甲国家德比更容易被边锋的爆发动作和回防距离决定走势。",
      en: "Le Classique often swings on how much explosive work the wide attackers can keep repeating.",
    },
    home: {
      teamId: "paris-saint-germain",
      fatigue: 47,
      squadAvailability: 94,
      matchDensity: 2,
      restDays: 6,
      travelKm: 320,
      recentResults: ["W", "W", "W", "D", "W"],
      momentumLabels: ["LIL(H)", "MON(A)", "REN(H)", "NIC(A)", "LYO(H)"],
      keyAbsent: [],
      keyFatigued: [
        {
          playerSlug: "ousmane-dembele",
          name: "Ousmane Dembele",
          age: 29,
          minutes14d: 262,
          level: "medium",
          note: {
            zh: "冲刺和变向频率高，但总量还在安全边缘内。",
            en: "Sprint and change-of-direction load is high, but total volume is still near the safe edge.",
          },
        },
        {
          name: "Vitinha",
          age: 26,
          minutes14d: 228,
          level: "low",
          note: {
            zh: "节奏控制任务稳定，恢复质量优于平均线。",
            en: "Rhythm-control work has been steady and the recovery quality sits above average.",
          },
        },
      ],
      schedule: [
        { day: -11, opponent: "LIL", home: true, competitionShort: "L1" },
        { day: -7, opponent: "MON", home: false, competitionShort: "L1" },
        { day: -3, opponent: "REN", home: true, competitionShort: "L1" },
        { day: 0, opponent: "OM", home: true, competitionShort: "L1", current: true },
        { day: 5, opponent: "NAN", home: false, competitionShort: "L1" },
      ],
      aiSummary: {
        zh: "巴黎近两周的负荷控制得比较理想，阵容完整度也维持在高位，因此比赛前的状态轮廓很干净。只要边路爆发点不被迫连续打满，他们会更像主导节奏的一方。",
        en: "PSG have managed their recent load well and squad availability remains high, which creates a very clean pre-match profile. As long as the explosive wide players do not have to play full load, they project as the side dictating tempo.",
      },
      statusNote: {
        zh: "他们更适合从控球和压迫回收里慢慢把比赛拉开。",
        en: "They are better suited to opening the game gradually through possession and pressure recoveries.",
      },
      formationHealth: { available: 10, doubtful: 0, absent: 0 },
    },
    away: {
      teamId: "marseille",
      fatigue: 62,
      squadAvailability: 83,
      matchDensity: 4,
      restDays: 3,
      travelKm: 760,
      recentResults: ["W", "D", "L", "W", "W"],
      momentumLabels: ["LOR(H)", "MON(A)", "STR(H)", "BRE(A)", "TOU(H)"],
      keyAbsent: ["Jordan Veretout"],
      keyFatigued: [
        {
          name: "Mason Greenwood",
          age: 25,
          minutes14d: 312,
          level: "high",
          note: {
            zh: "进攻端几乎所有爆点都堆在他身上。",
            en: "Too much of the explosive attacking burden has concentrated on him.",
          },
        },
        {
          name: "Pierre-Emerick Aubameyang",
          age: 37,
          minutes14d: 280,
          level: "medium",
          note: {
            zh: "冲刺总量可控，但年龄因素会放大恢复差异。",
            en: "Sprint volume is manageable, but age makes every recovery gap matter more.",
          },
        },
      ],
      schedule: [
        { day: -10, opponent: "LOR", home: true, competitionShort: "L1" },
        { day: -6, opponent: "MON", home: false, competitionShort: "L1" },
        { day: -3, opponent: "STR", home: true, competitionShort: "L1" },
        { day: 0, opponent: "PSG", home: false, competitionShort: "L1", current: true },
        { day: 4, opponent: "REI", home: true, competitionShort: "L1" },
      ],
      aiSummary: {
        zh: "马赛最近的赛程更密，核心攻击手的负荷也偏重，因此状态稳定性略逊。想把比赛变成五五开，他们更需要比赛进入高波动和反击对冲的区间。",
        en: "Marseille have been on the denser schedule and their main attackers are carrying heavier load, so the stability profile is weaker. To push this toward a coin flip, they need the match to become volatile and transition-heavy.",
      },
      statusNote: {
        zh: "他们更需要用纵向冲击制造短时间高收益回合。",
        en: "They need vertical attacks that create high-value moments in short bursts.",
      },
      formationHealth: { available: 8, doubtful: 1, absent: 1 },
    },
  },
  {
    id: "match-arg-fra",
    slug: "argentina-vs-france",
    bucket: "week",
    competitionId: "fifa-world-cup",
    stage: "Group B · Matchday 2",
    kickoffLabel: "Fri, Jun 19 · 18:00",
    startsAt: "2026-06-19T18:00:00Z",
    venue: "MetLife Stadium, New Jersey",
    featuredPlayerSlug: "kylian-mbappe",
    verdict: {
      zh: "两队俱乐部赛季负荷都偏高，但法国的旅行链路更短，阿根廷的恢复窗口更复杂。",
      en: "Both squads carry heavy club-season load, but France have the shorter travel chain and Argentina face the more complex recovery window.",
    },
    spotlight: {
      zh: "世界杯语境下，跨洲旅行和集训地切换会放大疲劳差异。",
      en: "In World Cup mode, cross-continent travel and camp switching amplify every fatigue gap.",
    },
    home: {
      teamId: "argentina",
      fatigue: 58,
      squadAvailability: 91,
      matchDensity: 3,
      restDays: 4,
      travelKm: 2420,
      recentResults: ["W", "W", "D", "W", "W"],
      momentumLabels: ["URU", "COL", "BRA", "PAR", "JPN"],
      keyAbsent: [],
      keyFatigued: [
        {
          playerSlug: "lautaro-martinez",
          name: "Lautaro Martínez",
          age: 29,
          minutes14d: 290,
          level: "medium",
          note: {
            zh: "联赛尾声与国家队衔接带来连续负荷。",
            en: "Club run-in load has carried into the national-team window.",
          },
        },
        {
          name: "Enzo Fernández",
          age: 25,
          minutes14d: 264,
          level: "medium",
          note: {
            zh: "中场大范围覆盖和长距离旅行叠加。",
            en: "Midfield range and long-distance travel are stacking together.",
          },
        },
      ],
      schedule: [
        { day: -6, opponent: "JPN", home: true, competitionShort: "WC" },
        { day: 0, opponent: "FRA", home: true, competitionShort: "WC", current: true },
        { day: 4, opponent: "MEX", home: false, competitionShort: "WC" },
      ],
      aiSummary: {
        zh: "阿根廷的大多数核心球员都刚经历高强度俱乐部赛季，世界杯前段的旅行链路也更复杂。阵容完整度不错，但恢复节奏并不轻松。",
        en: "Most of Argentina's core players have just come off heavy club seasons, and their early-tournament travel chain is more complex. Availability is healthy, but recovery rhythm is not especially gentle.",
      },
      statusNote: {
        zh: "他们更需要在控球阶段减少无效消耗。",
        en: "They need controlled possession phases to trim unnecessary physical waste.",
      },
      formationHealth: { available: 10, doubtful: 0, absent: 0 },
    },
    away: {
      teamId: "france",
      fatigue: 50,
      squadAvailability: 93,
      matchDensity: 2,
      restDays: 5,
      travelKm: 1460,
      recentResults: ["W", "D", "W", "W", "W"],
      momentumLabels: ["USA", "NED", "POR", "BEL", "MAR"],
      keyAbsent: ["Dayot Upamecano"],
      keyFatigued: [
        {
          playerSlug: "kylian-mbappe",
          name: "Kylian Mbappé",
          age: 28,
          minutes14d: 248,
          level: "medium",
          note: {
            zh: "高爆发动作仍多，但总量控制得更好。",
            en: "The explosive actions are still there, but the total load is better managed.",
          },
        },
        {
          name: "Aurélien Tchouaméni",
          age: 27,
          minutes14d: 222,
          level: "low",
          note: {
            zh: "恢复质量较优，是中场稳定器。",
            en: "Recovery quality is strong, making him a midfield stabilizer.",
          },
        },
      ],
      schedule: [
        { day: -5, opponent: "USA", home: true, competitionShort: "WC" },
        { day: 0, opponent: "ARG", home: false, competitionShort: "WC", current: true },
        { day: 4, opponent: "POL", home: true, competitionShort: "WC" },
      ],
      aiSummary: {
        zh: "法国的俱乐部赛季负荷同样不低，但国家队集训和旅行安排更紧凑，因此赛前状态稍微更整洁。最大的变量还是前场核心的高爆发动作会不会堆积。",
        en: "France also bring a heavy club-season burden, but their national-team camp and travel plan are tighter, so the pre-match state looks a touch cleaner. The main watchpoint is whether the front line's explosive actions begin to stack.",
      },
      statusNote: {
        zh: "他们在世界杯模式下更像一支恢复计划清晰的球队。",
        en: "In tournament mode they look like the side with the cleaner recovery plan.",
      },
      formationHealth: { available: 9, doubtful: 1, absent: 1 },
    },
  },
];

export const players: PlayerProfile[] = [
  {
    slug: "mo-salah",
    teamId: "liverpool",
    name: "Mo Salah",
    position: "RW",
    age: 33,
    nationality: "Egypt",
    fatigueScore: 74,
    level: "high",
    last14Minutes: 352,
    seasonMinutes: 3670,
    startsLast5: 5,
    nextFixture: "vs Man City · Premier League",
    summary: {
      zh: "萨拉赫仍然维持顶级输出，但最近两周的连续高负荷正在逼近他本赛季最紧张的恢复窗口。",
      en: "Salah is still producing at elite level, but the last two weeks have pushed him close to his tightest recovery window of the season.",
    },
    workloadHistory: [72, 86, 78, 92, 88, 94, 84, 76],
    workloadLabels: ["W25", "W26", "W27", "W28", "W29", "W30", "W31", "W32"],
    fatigueTrend: [48, 53, 57, 61, 67, 70, 72, 74],
    fatigueLabels: ["-30d", "-25d", "-20d", "-15d", "-10d", "-7d", "-3d", "Now"],
    injuries: [
      {
        date: "2026-02-18",
        label: {
          zh: "腘绳肌紧张，休战 6 天",
          en: "Hamstring tightness, out for 6 days",
        },
        duration: "6d",
      },
    ],
    rotationPrediction: {
      zh: "如果利物浦未来 7 天继续双赛，萨拉赫下一场杯赛被提前换下的概率会明显上升。",
      en: "If Liverpool keep a two-match week, Salah's probability of an early cup substitution rises noticeably.",
    },
    comparison: [
      {
        label: { zh: "与同位置平均负荷对比", en: "Vs positional average load" },
        value: "+18%",
        note: {
          zh: "比英超同位置核心球员更重。",
          en: "He is carrying a heavier load than most elite PL wide forwards.",
        },
        tone: "danger",
      },
      {
        label: { zh: "恢复天数", en: "Recovery days" },
        value: "3.0",
        note: {
          zh: "连续高负荷下恢复偏短。",
          en: "Recovery windows are short under continuous load.",
        },
        tone: "warning",
      },
    ],
  },
  {
    slug: "rodri",
    teamId: "man-city",
    name: "Rodri",
    position: "DM",
    age: 29,
    nationality: "Spain",
    fatigueScore: 41,
    level: "low",
    last14Minutes: 180,
    seasonMinutes: 3128,
    startsLast5: 3,
    nextFixture: "@ Liverpool · Premier League",
    summary: {
      zh: "罗德里目前的分钟数控制得很理想，进入比赛时更像一名拥有恢复优势的节奏锚点。",
      en: "Rodri's recent minute load has been managed well, so he projects as a rhythm anchor with a clear recovery edge.",
    },
    workloadHistory: [58, 63, 60, 61, 57, 54, 48, 44],
    workloadLabels: ["W25", "W26", "W27", "W28", "W29", "W30", "W31", "W32"],
    fatigueTrend: [54, 51, 50, 48, 46, 45, 43, 41],
    fatigueLabels: ["-30d", "-25d", "-20d", "-15d", "-10d", "-7d", "-3d", "Now"],
    injuries: [],
    rotationPrediction: {
      zh: "在目前负荷水平下，罗德里继续首发的概率很高，轮换风险偏低。",
      en: "At the current load level, Rodri remains a strong bet to start again with low rotation risk.",
    },
    comparison: [
      {
        label: { zh: "与同位置平均负荷对比", en: "Vs positional average load" },
        value: "-9%",
        note: {
          zh: "比大多数顶级后腰更轻。",
          en: "He is arriving lighter than most elite holding midfielders.",
        },
        tone: "positive",
      },
      {
        label: { zh: "恢复天数", en: "Recovery days" },
        value: "6.0",
        note: {
          zh: "恢复窗口充足。",
          en: "Recovery window has been healthy.",
        },
        tone: "positive",
      },
    ],
  },
  {
    slug: "jude-bellingham",
    teamId: "real-madrid",
    name: "Jude Bellingham",
    position: "AM",
    age: 22,
    nationality: "England",
    fatigueScore: 63,
    level: "medium",
    last14Minutes: 340,
    seasonMinutes: 3495,
    startsLast5: 5,
    nextFixture: "vs Barcelona · La Liga",
    summary: {
      zh: "贝林厄姆承担的全场覆盖任务太多，当前最关键的不是输出能力，而是高强度动作后的恢复质量。",
      en: "Bellingham is covering too much ground on both sides of the ball. The key question is not output, but how well he recovers from repeated high-intensity actions.",
    },
    workloadHistory: [66, 74, 82, 88, 90, 86, 84, 81],
    workloadLabels: ["W25", "W26", "W27", "W28", "W29", "W30", "W31", "W32"],
    fatigueTrend: [42, 47, 51, 55, 58, 60, 62, 63],
    fatigueLabels: ["-30d", "-25d", "-20d", "-15d", "-10d", "-7d", "-3d", "Now"],
    injuries: [
      {
        date: "2026-01-23",
        label: {
          zh: "脚踝扭伤，休战 10 天",
          en: "Ankle sprain, out for 10 days",
        },
        duration: "10d",
      },
    ],
    rotationPrediction: {
      zh: "如果皇马在未来一周继续双线拉满，贝林厄姆被轮换或至少被限制出场时间的概率在上升。",
      en: "If Madrid keep a full two-front schedule, Bellingham's odds of rotation or at least managed minutes are rising.",
    },
    comparison: [
      {
        label: { zh: "前插负荷", en: "Advanced run load" },
        value: "Top 8%",
        note: {
          zh: "前插和回追都处于高档。",
          en: "Both advanced and recovery runs remain in the high tier.",
        },
        tone: "danger",
      },
      {
        label: { zh: "近 14 天分钟数", en: "Last 14-day minutes" },
        value: "340",
        note: {
          zh: "已接近风险线。",
          en: "The recent minute total is approaching the red line.",
        },
        tone: "warning",
      },
    ],
  },
  {
    slug: "lamine-yamal",
    teamId: "barcelona",
    name: "Lamine Yamal",
    position: "RW",
    age: 18,
    nationality: "Spain",
    fatigueScore: 39,
    level: "low",
    last14Minutes: 260,
    seasonMinutes: 2610,
    startsLast5: 4,
    nextFixture: "@ Real Madrid · La Liga",
    summary: {
      zh: "亚马尔的比赛使用率很高，但目前恢复窗口依然健康，体能上还没有进入明显风险区。",
      en: "Yamal is being used aggressively, but the recovery windows still look healthy and the physical profile is not yet in the danger zone.",
    },
    workloadHistory: [44, 49, 52, 54, 57, 61, 53, 50],
    workloadLabels: ["W25", "W26", "W27", "W28", "W29", "W30", "W31", "W32"],
    fatigueTrend: [31, 32, 33, 35, 36, 38, 38, 39],
    fatigueLabels: ["-30d", "-25d", "-20d", "-15d", "-10d", "-7d", "-3d", "Now"],
    injuries: [],
    rotationPrediction: {
      zh: "只要巴萨保持当前赛程密度，亚马尔继续首发的概率仍然很高。",
      en: "As long as Barca stay on the current schedule density, Yamal remains highly likely to keep starting.",
    },
    comparison: [
      {
        label: { zh: "年龄修正", en: "Age modifier" },
        value: "-6%",
        note: {
          zh: "年轻球员恢复速度更快。",
          en: "Youth helps him recover a little quicker than older peers.",
        },
        tone: "positive",
      },
      {
        label: { zh: "近 14 天分钟数", en: "Last 14-day minutes" },
        value: "260",
        note: {
          zh: "处于可控范围。",
          en: "Still within a controllable range.",
        },
        tone: "positive",
      },
    ],
  },
  {
    slug: "lautaro-martinez",
    teamId: "inter",
    name: "Lautaro Martínez",
    position: "ST",
    age: 29,
    nationality: "Argentina",
    fatigueScore: 56,
    level: "medium",
    last14Minutes: 318,
    seasonMinutes: 3318,
    startsLast5: 4,
    nextFixture: "vs Bayern · Champions League",
    summary: {
      zh: "劳塔罗的整体负荷高于理想值，但仍然在可管理区间，关键在于是否需要连续承担全场终结任务。",
      en: "Lautaro sits above the ideal workload line but remains manageable. The key is whether he must shoulder another full-match finishing role.",
    },
    workloadHistory: [52, 60, 67, 74, 72, 70, 68, 65],
    workloadLabels: ["W25", "W26", "W27", "W28", "W29", "W30", "W31", "W32"],
    fatigueTrend: [39, 43, 47, 50, 53, 54, 55, 56],
    fatigueLabels: ["-30d", "-25d", "-20d", "-15d", "-10d", "-7d", "-3d", "Now"],
    injuries: [],
    rotationPrediction: {
      zh: "在欧冠主场这种级别的比赛里，他更像必须首发但需要精细管理出场时间的类型。",
      en: "In a home Champions League tie he still profiles as a must-start, but one whose minutes may need sharper management.",
    },
    comparison: [
      {
        label: { zh: "冲刺负荷", en: "Sprint load" },
        value: "Top 18%",
        note: {
          zh: "高于大多数顶级中锋。",
          en: "Above most elite central forwards.",
        },
        tone: "warning",
      },
      {
        label: { zh: "恢复天数", en: "Recovery days" },
        value: "4.0",
        note: {
          zh: "正常但不算宽裕。",
          en: "Reasonable, but not generous.",
        },
        tone: "warning",
      },
    ],
  },
  {
    slug: "jamal-musiala",
    teamId: "bayern",
    name: "Jamal Musiala",
    position: "AM",
    age: 23,
    nationality: "Germany",
    fatigueScore: 58,
    level: "medium",
    last14Minutes: 290,
    seasonMinutes: 2984,
    startsLast5: 4,
    nextFixture: "vs Dortmund · Bundesliga",
    summary: {
      zh: "穆西亚拉的爆发动作和持球推进仍是拜仁最锋利的创造来源，但这也让他的疲劳评估始终停留在观察区。",
      en: "Musiala's bursts and carries remain Bayern's sharpest creative source, which also keeps his fatigue profile in the watch zone.",
    },
    workloadHistory: [49, 54, 57, 60, 63, 66, 61, 58],
    workloadLabels: ["W25", "W26", "W27", "W28", "W29", "W30", "W31", "W32"],
    fatigueTrend: [40, 44, 47, 50, 53, 56, 57, 58],
    fatigueLabels: ["-30d", "-25d", "-20d", "-15d", "-10d", "-7d", "-3d", "Now"],
    injuries: [],
    rotationPrediction: {
      zh: "在强强对话里他大概率继续首发，但下半场被保护性换下的概率在上升。",
      en: "He is still highly likely to start the big games, though the chance of a protective second-half substitution is growing.",
    },
    comparison: [
      {
        label: { zh: "爆发动作负荷", en: "Explosive action load" },
        value: "Top 15%",
        note: {
          zh: "变向和持球推进是主要负荷来源。",
          en: "Direction changes and carrying volume drive most of the load.",
        },
        tone: "warning",
      },
      {
        label: { zh: "恢复天数", en: "Recovery days" },
        value: "5.0",
        note: {
          zh: "恢复窗口整体健康。",
          en: "The recovery windows have been broadly healthy.",
        },
        tone: "positive",
      },
    ],
  },
  {
    slug: "ousmane-dembele",
    teamId: "paris-saint-germain",
    name: "Ousmane Dembele",
    position: "RW",
    age: 29,
    nationality: "France",
    fatigueScore: 52,
    level: "medium",
    last14Minutes: 262,
    seasonMinutes: 2816,
    startsLast5: 4,
    nextFixture: "vs Marseille · Ligue 1",
    summary: {
      zh: "登贝莱的高频爆发动作仍然让他维持在观察区，但整体分钟数控制得比此前更理想。",
      en: "Dembele's repeated explosive actions still keep him in the watch zone, but the overall minute management is cleaner than before.",
    },
    workloadHistory: [46, 51, 55, 58, 60, 63, 57, 54],
    workloadLabels: ["W25", "W26", "W27", "W28", "W29", "W30", "W31", "W32"],
    fatigueTrend: [38, 41, 44, 46, 48, 50, 51, 52],
    fatigueLabels: ["-30d", "-25d", "-20d", "-15d", "-10d", "-7d", "-3d", "Now"],
    injuries: [],
    rotationPrediction: {
      zh: "只要巴黎继续维持当前赛程密度，登贝莱更像会继续首发但被精细管理出场时间的球员。",
      en: "If PSG keep the current schedule density, Dembele still looks like a likely starter whose minutes will be managed carefully.",
    },
    comparison: [
      {
        label: { zh: "一对一动作密度", en: "1v1 action density" },
        value: "Elite",
        note: {
          zh: "动作类型对疲劳非常敏感。",
          en: "The action profile is highly sensitive to fatigue accumulation.",
        },
        tone: "warning",
      },
      {
        label: { zh: "近 14 天分钟数", en: "Last 14-day minutes" },
        value: "262",
        note: {
          zh: "仍在可控区间内。",
          en: "Still inside a manageable range.",
        },
        tone: "positive",
      },
    ],
  },
  {
    slug: "kylian-mbappe",
    teamId: "france",
    name: "Kylian Mbappé",
    position: "LW",
    age: 28,
    nationality: "France",
    fatigueScore: 53,
    level: "medium",
    last14Minutes: 248,
    seasonMinutes: 3412,
    startsLast5: 3,
    nextFixture: "vs Argentina · World Cup",
    summary: {
      zh: "姆巴佩的体能状态整体可控，但高爆发动作依然会让他的赛前评估保持在观察区。",
      en: "Mbappé's overall condition is manageable, though repeated explosive actions keep his pre-match profile in the watch zone.",
    },
    workloadHistory: [61, 66, 63, 68, 64, 59, 55, 52],
    workloadLabels: ["W25", "W26", "W27", "W28", "W29", "W30", "W31", "W32"],
    fatigueTrend: [46, 48, 49, 50, 52, 53, 53, 53],
    fatigueLabels: ["-30d", "-25d", "-20d", "-15d", "-10d", "-7d", "-3d", "Now"],
    injuries: [
      {
        date: "2026-03-11",
        label: {
          zh: "大腿轻微不适，休战 4 天",
          en: "Minor thigh issue, out for 4 days",
        },
        duration: "4d",
      },
    ],
    rotationPrediction: {
      zh: "法国大概率继续首发姆巴佩，但会努力避免他在无球阶段承担过多回防距离。",
      en: "France are still highly likely to start Mbappé, but will want to protect him from excessive off-ball recovery runs.",
    },
    comparison: [
      {
        label: { zh: "爆发动作密度", en: "Explosive action density" },
        value: "Elite",
        note: {
          zh: "对疲劳非常敏感的动作类型。",
          en: "The type of action most sensitive to accumulated fatigue.",
        },
        tone: "warning",
      },
      {
        label: { zh: "旅行影响", en: "Travel impact" },
        value: "Low",
        note: {
          zh: "法国集训和比赛链路更短。",
          en: "France have the shorter camp-to-match travel chain.",
        },
        tone: "positive",
      },
    ],
  },
];

export const newsItems: NewsItem[] = [
  {
    id: "news-world-cup-recovery",
    slug: "world-cup-recovery-windows",
    href: "/world-cup",
    competitionIds: ["fifa-world-cup"],
    category: {
      zh: "世界杯",
      en: "World Cup",
    },
    title: {
      zh: "世界杯恢复窗口开始拉开差距，集训与旅行路径成核心变量",
      en: "Recovery windows are already separating World Cup contenders as camps and travel routes take over",
    },
    summary: {
      zh: "阿根廷与法国的赛前体能画像已经开始分化，跨洲旅行和训练基地切换正在放大细节差距。",
      en: "Argentina and France are already diverging in pre-match condition, with intercontinental travel and camp changes magnifying every small detail.",
    },
    source: "SonarFC",
    publishedLabel: "2h ago",
    accent: "#6EC1E4",
  },
  {
    id: "news-ucl-load-battle",
    slug: "champions-league-load-battle",
    href: "/competition/champions-league",
    competitionIds: ["champions-league"],
    category: {
      zh: "欧冠",
      en: "Champions League",
    },
    title: {
      zh: "欧冠淘汰赛进入负荷管理阶段，恢复质量开始比状态更重要",
      en: "Champions League knockout ties are entering the load-management stage, where recovery quality matters more than raw form",
    },
    summary: {
      zh: "顶级强队的赛前差异越来越像恢复计划的差异，主力的连续首发已不再只是战术问题。",
      en: "The pre-match edge between elite sides increasingly comes down to recovery planning rather than tactics alone.",
    },
    source: "SonarFC",
    publishedLabel: "3h ago",
    accent: "#1D4ED8",
  },
  {
    id: "news-ucl-madrid-psg",
    slug: "madrid-psg-recovery-window",
    href: "/match/real-madrid-vs-psg",
    competitionIds: ["champions-league"],
    category: {
      zh: "欧冠",
      en: "Champions League",
    },
    title: {
      zh: "皇马 vs 巴黎：这组半决赛的真正差距，可能出现在恢复窗口而不是星味",
      en: "Real Madrid vs PSG may be decided by recovery windows rather than star power",
    },
    summary: {
      zh: "皇马中前场连续高使用率已经逼近风险区，巴黎则更像在等待比赛后段的速度优势。",
      en: "Madrid's attacking spine is nearing the risk line for usage, while PSG look built to exploit a late pace advantage.",
    },
    source: "SonarFC",
    publishedLabel: "5h ago",
    accent: "#8B5CF6",
  },
  {
    id: "news-ucl-barca-dortmund",
    slug: "barca-dortmund-rhythm-control",
    href: "/match/barcelona-vs-dortmund-ucl",
    competitionIds: ["champions-league"],
    category: {
      zh: "欧冠",
      en: "Champions League",
    },
    title: {
      zh: "巴萨 vs 多特：控制节奏的一方，正在体能画像上先拿到主动权",
      en: "Barca vs Dortmund is shaping into a rhythm-control battle where the fresher side owns the first edge",
    },
    summary: {
      zh: "巴萨的密度和旅行负担都更轻，多特想把比赛拉回均势，需要更高波动的开放节奏。",
      en: "Barca are lighter on density and travel, so Dortmund need a more volatile open game to pull this tie back toward even.",
    },
    source: "SonarFC",
    publishedLabel: "6h ago",
    accent: "#F59E0B",
  },
  {
    id: "news-liverpool-city",
    slug: "liverpool-city-fatigue-story",
    href: "/match/liverpool-vs-man-city",
    competitionIds: ["premier-league"],
    category: {
      zh: "英超",
      en: "Premier League",
    },
    title: {
      zh: "利物浦 vs 曼城：主场势头和恢复窗口正在形成最典型的对冲局",
      en: "Liverpool vs City is becoming the cleanest clash between home momentum and recovery edge",
    },
    summary: {
      zh: "利物浦的高疲劳并没有直接拖垮竞争力，但会把比赛后段的不确定性持续放大。",
      en: "Liverpool's heavy fatigue has not killed competitiveness, but it keeps amplifying late-game volatility.",
    },
    source: "SonarFC",
    publishedLabel: "4h ago",
    accent: "#C8102E",
  },
  {
    id: "news-clasico-depth",
    slug: "clasico-depth-and-recovery",
    href: "/match/real-madrid-vs-barcelona",
    competitionIds: ["la-liga"],
    category: {
      zh: "西甲",
      en: "La Liga",
    },
    title: {
      zh: "国家德比前瞻：阵容深度与恢复质量正取代近期战绩成为主线",
      en: "Clasico preview: squad depth and recovery quality are replacing recent form as the main storyline",
    },
    summary: {
      zh: "皇马赛程更重，巴萨则在完整度上更稳定，这会直接影响比赛的后段强度。",
      en: "Madrid carry the heavier schedule load, while Barca arrive with cleaner availability, a contrast that should shape the final phases of the match.",
    },
    source: "SonarFC",
    publishedLabel: "5h ago",
    accent: "#A50044",
  },
  {
    id: "news-serie-a-transition",
    slug: "serie-a-transition-battle",
    href: "/competition/serie-a",
    competitionIds: ["serie-a"],
    category: {
      zh: "意甲",
      en: "Serie A",
    },
    title: {
      zh: "意甲强强对话正在回到转换速度的较量，体能差会先从中场覆盖暴露",
      en: "Serie A heavyweights are turning back into transition battles where the fatigue gap first appears in midfield coverage",
    },
    summary: {
      zh: "国米和那不勒斯的赛前画像都不差，但恢复窗口的微小差异会直接影响压迫持续性。",
      en: "Inter and Napoli both enter in decent shape, but tiny differences in recovery windows may decide how long the press can survive.",
    },
    source: "SonarFC",
    publishedLabel: "7h ago",
    accent: "#0085CA",
  },
  {
    id: "news-bundesliga-press",
    slug: "bundesliga-press-sustainability",
    href: "/competition/bundesliga",
    competitionIds: ["bundesliga"],
    category: {
      zh: "德甲",
      en: "Bundesliga",
    },
    title: {
      zh: "德甲焦点战的分水岭仍是压迫是否能持续 90 分钟",
      en: "The defining question in Bundesliga headline games remains whether the press survives all 90 minutes",
    },
    summary: {
      zh: "拜仁的恢复画像更整洁，而多特需要把比赛变得更开放，才能抵消体能差。",
      en: "Bayern own the cleaner recovery profile, while Dortmund need volatility to offset the physical gap.",
    },
    source: "SonarFC",
    publishedLabel: "9h ago",
    accent: "#FDE100",
  },
  {
    id: "news-ligue1-burst",
    slug: "ligue1-burst-load",
    href: "/competition/ligue-1",
    competitionIds: ["ligue-1"],
    category: {
      zh: "法甲",
      en: "Ligue 1",
    },
    title: {
      zh: "法甲国家德比的关键仍是边锋的爆发动作能否持续输出",
      en: "Le Classique still swings on whether the explosive wide threats can keep repeating their actions",
    },
    summary: {
      zh: "巴黎的恢复质量更好，马赛则更依赖高波动回合带来的单次收益。",
      en: "PSG hold the cleaner recovery edge, while Marseille depend on volatile high-payoff moments.",
    },
    source: "SonarFC",
    publishedLabel: "11h ago",
    accent: "#0A2A66",
  },
];

export const worldCupTeams: WorldCupTeamProfile[] = [
  {
    teamId: "argentina",
    group: "B",
    clubMinutesIndex: 78,
    travelKm: 2420,
    restDaysBetweenMatches: 4,
    keyRiskCount: 3,
    outlook: {
      zh: "高强度俱乐部赛季叠加跨洲旅行，恢复计划必须更保守。",
      en: "A heavy club season plus intercontinental travel means the recovery plan needs to stay conservative.",
    },
    travelLegs: [
      { from: "Milan", to: "Miami Camp", distanceKm: 7970, timezoneShift: -6 },
      { from: "Miami Camp", to: "New Jersey", distanceKm: 1750, timezoneShift: 0 },
      { from: "New Jersey", to: "Mexico City", distanceKm: 3360, timezoneShift: -1 },
    ],
    recoveryMatrix: [
      { opponent: "Japan", city: "New Jersey", daysBetween: 4 },
      { opponent: "France", city: "New Jersey", daysBetween: 4 },
      { opponent: "Mexico", city: "Mexico City", daysBetween: 4 },
    ],
  },
  {
    teamId: "france",
    group: "B",
    clubMinutesIndex: 73,
    travelKm: 1460,
    restDaysBetweenMatches: 4,
    keyRiskCount: 2,
    outlook: {
      zh: "核心球员同样负荷不低，但国家队集训和移动安排更整齐。",
      en: "The core group still arrives heavily loaded, but the camp and movement plan is cleaner.",
    },
    travelLegs: [
      { from: "Madrid", to: "Houston Camp", distanceKm: 8040, timezoneShift: -7 },
      { from: "Houston Camp", to: "New Jersey", distanceKm: 2280, timezoneShift: 1 },
      { from: "New Jersey", to: "Toronto", distanceKm: 556, timezoneShift: 0 },
    ],
    recoveryMatrix: [
      { opponent: "USA", city: "Houston", daysBetween: 5 },
      { opponent: "Argentina", city: "New Jersey", daysBetween: 4 },
      { opponent: "Poland", city: "Toronto", daysBetween: 4 },
    ],
  },
  {
    teamId: "england",
    group: "D",
    clubMinutesIndex: 69,
    travelKm: 1840,
    restDaysBetweenMatches: 5,
    keyRiskCount: 2,
    outlook: {
      zh: "整体负荷可控，但英格兰需要避免让边锋连续承担全场回追任务。",
      en: "The global load is manageable, but England need to protect wide players from full-match recovery runs.",
    },
    travelLegs: [
      { from: "London", to: "New York Camp", distanceKm: 5560, timezoneShift: -5 },
      { from: "New York Camp", to: "Boston", distanceKm: 346, timezoneShift: 0 },
      { from: "Boston", to: "Atlanta", distanceKm: 1510, timezoneShift: 0 },
    ],
    recoveryMatrix: [
      { opponent: "Korea", city: "Boston", daysBetween: 5 },
      { opponent: "Netherlands", city: "Atlanta", daysBetween: 5 },
      { opponent: "Denmark", city: "Dallas", daysBetween: 4 },
    ],
  },
  {
    teamId: "brazil",
    group: "E",
    clubMinutesIndex: 71,
    travelKm: 1980,
    restDaysBetweenMatches: 4,
    keyRiskCount: 2,
    outlook: {
      zh: "核心创造型球员负荷较高，但南美球队对旅行切换更适应。",
      en: "Creative core players carry heavy minutes, but travel transitions are slightly more familiar for the squad.",
    },
    travelLegs: [
      { from: "Barcelona", to: "Los Angeles Camp", distanceKm: 9670, timezoneShift: -9 },
      { from: "Los Angeles Camp", to: "Seattle", distanceKm: 1540, timezoneShift: 0 },
      { from: "Seattle", to: "San Francisco", distanceKm: 1090, timezoneShift: 0 },
    ],
    recoveryMatrix: [
      { opponent: "USA", city: "Seattle", daysBetween: 4 },
      { opponent: "Croatia", city: "San Francisco", daysBetween: 4 },
      { opponent: "Senegal", city: "Los Angeles", daysBetween: 5 },
    ],
  },
];

export const defaultPreferences: UserPreferencesState = {
  theme: "light",
  locale: "zh",
  followedTeams: ["liverpool", "real-madrid", "argentina"],
  followedCompetitions: ["premier-league", "champions-league", "fifa-world-cup"],
  notifications: {
    preMatch: true,
    dailyDigest: false,
  },
};

export function getCompetitionById(id: string) {
  return competitions.find((competition) => competition.id === id);
}

export function getCompetitionBySlug(slug: string) {
  return competitions.find((competition) => competition.slug === slug);
}

export function getTeamById(id: string) {
  return teams.find((team) => team.id === id);
}

export function getMatchBySlug(slug: string) {
  return matches.find((match) => match.slug === slug);
}

export function getMatchesByBucket(bucket: MatchBucket) {
  return matches.filter((match) => match.bucket === bucket);
}

export function getMatchesByCompetition(competitionId: string) {
  return matches.filter((match) => match.competitionId === competitionId);
}

export function getPlayerBySlug(slug: string) {
  return players.find((player) => player.slug === slug);
}

export function getPlayersForTeam(teamId: string) {
  return players.filter((player) => player.teamId === teamId);
}

export function getWorldCupTeamById(teamId: string) {
  return worldCupTeams.find((team) => team.teamId === teamId);
}

export function getNewsByCompetition(competitionId: string) {
  return newsItems.filter((item) => item.competitionIds.includes(competitionId));
}

export function getUpcomingMatchesForTeams(teamIds: string[]) {
  return matches.filter(
    (match) => teamIds.includes(match.home.teamId) || teamIds.includes(match.away.teamId)
  );
}
